In [1]:
!pip install matplotlib seaborn pandas streamlit --break-system-packages

Collecting matplotlib
  Downloading matplotlib-3.10.7-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting streamlit
  Downloading streamlit-1.51.0-py3-none-any.whl.metadata (9.5 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.60.1-cp313-cp313-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (112 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
Collecting numpy>=1.23 (from matplotlib)
  Downloading numpy-2.3.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.13/site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.0.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3.13/site-packages (from matplotlib) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.13/site-packages (from pandas) (2025.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting altair!=5.4.0,!=5.4.1,<6,>=4.0 (from streamlit)
  Downloading altair-5.5.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<7,>=4.0 (from streamlit)
  Downloading cachetools-6.2.1-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in /usr/lib/python3.13/site-packages (from streamlit) (8.2.1)
Collecting protobuf<7,>=3.20 (from streamlit)
  Downloading protobuf-6.33.0-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting pyarrow<22,>=7.0 (from streamlit)
  Downloading pyarrow-21.0.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: requests<3,>=2.27 in /usr/lib/python3.13/site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/lib/python3.13/site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/lib/python3.13/site-packages (from streamlit) (6.5.2)
Requirement already satisfied: jinja2 in /usr/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)
Collecting narwhals>=1.14.2 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit)
  Downloading narwhals-2.10.1-py3-none-any.whl.metadata (11 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3.13/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.7-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 739.7 kB/s  0:00:11 eta 0:00:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading pandas-2.3.3-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 907.1 kB/s  0:00:13m0:00:0100:01
Downloading streamlit-1.51.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 525.8 kB/s  0:00:19m0:00:010:01
Downloading altair-5.5.0-py3-none-any.whl (731 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.2/731.2 kB 576.0 kB/s  0:00:01 eta 0:00:01
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-6.2.1-py3-none-any.whl (11 kB)
Downloading gitpython-3.1.45-py3-none-any.whl (208 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading numpy-2.3.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 623.1 kB/s  0:00:26m0:00:0100:02
Downloading pillow-12.0.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 968.2 kB/s  0:00:07 eta 0:00:01
Downloading protobuf-6.33.0-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Downloading pyarrow-21.0.0-cp313-cp313-manylinux_2_28_x86_64.whl (42.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 668.2 kB/s  0:00:59m0:00:0100:02
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 955.5 kB/s  0:00:07m0:00:0100:01
Downloading smmap-5.0.2-py3-none-any.whl (24 kB)
Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)
Downloading contourpy-1.3.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.60.1-cp313-cp313-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 746.4 kB/s  0:00:06 eta 0:00:01
Downloading kiwisolver-1.4.9-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 331.9 kB/s  0:00:04 eta 0:00:01
Downloading narwhals-2.10.1-py3-none-any.whl (419 kB)
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: watchdog, tzdata, toml, tenacity, smmap, pyparsing, pyarrow, protobuf, pillow, numpy, narwhals, kiwisolver, fonttools, cycler, cachetools, blinker, pydeck, pandas, gitdb, contourpy, matplotlib, gitpython, seaborn, altair, streamlit
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25/25 [streamlit]25 [streamlit]]
Successfully installed altair-5.5.0 blinker-1.9.0 cachetools-6.2.1 contourpy-1.3.3 cycler-0.12.1 fonttools-4.60.1 gitdb-4.0.12 gitpython-3.1.45 kiwisolver-1.4.9 matplotlib-3.10.7 narwhals-2.10.1 numpy-2.3.4 pandas-2.3.3 pillow-12.0.0 protobuf-6.33.0 pyarrow-21.0.0 pydeck-0.9.1 pyparsing-3.2.5 seaborn-0.13.2 smmap-5.0.2 streamlit-1.51.0 tenacity-9.1.2 toml-0.10.2 tzdata-2025.2 watchdog-6.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [2]:
%matplotlib inline
import os
import gc

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
BASE_DATA_FOLDER = os.path.join(".", "base_data")

In [3]:
def read_csv(file:str) -> pd.DataFrame:
    ENCODING="windows-1252"
    SEP=";"
    return pd.read_csv(file, encoding=ENCODING, sep=SEP)

In [10]:
def concat_path(file:str) -> str:
    return os.path.join(BASE_DATA_FOLDER, file)

In [13]:
csv_files = list(filter(lambda file: 'csv' in file, [concat_path(file)  for file in os.listdir(path=BASE_DATA_FOLDER)]))
csv_files

['./base_data/base_chegadas_2025_acum_08_agosto.csv',
 './base_data/chegadas_2023.csv',
 './base_data/chegadas_2024.csv']

In [14]:
data_2025 = read_csv(csv_files[0])
data_2025.head()

  Via_de_acesso              UF nome_pais_correto      mes   ano  Chegadas
0         Aérea  Rio de Janeiro       Afeganistão  Janeiro  2025         1
1         Aérea       São Paulo       Afeganistão  Janeiro  2025         3
2     Terrestre          Paraná       Afeganistão  Janeiro  2025         2
3     Terrestre  Santa Catarina       Afeganistão  Janeiro  2025         4
4     Terrestre  Santa Catarina       Afeganistão  Janeiro  2025         2

In [15]:
data_2023 = read_csv(csv_files[1])
data_2023.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,América do Sul,4,Peru,34,Acre,1,Aéreo,1,2023,Novembro,11,0
1,América do Sul,4,Peru,34,Acre,1,Aéreo,1,2023,Novembro,11,0
2,Ásia,5,Outros países,56,Outras Unidades da Federação,99,Aéreo,1,2023,Junho,6,0
3,Europa,6,Alemanha,57,Outras Unidades da Federação,99,Aéreo,1,2023,Janeiro,1,12
4,Europa,6,Alemanha,57,Outras Unidades da Federação,99,Aéreo,1,2023,Fevereiro,2,10

In [16]:
data_2024 = read_csv(csv_files[2])
data_2024.head()

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,Europa,6,Alemanha,57,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,10
1,América do Sul,4,Argentina,26,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,1197
2,Europa,6,Bélgica,59,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,3
3,América do Norte,3,Canadá,23,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,2
4,América do Sul,4,Chile,28,Outras Unidades da Federação,99,Aérea,1,2024,Janeiro,1,1

In [32]:
countries_continents_2024 = data_2024[["Continente","País"]]
countries_continents_2023 = data_2023[["Continente","País"]]

matching_continets_per_country = pd.concat([countries_continents_2024,countries_continents_2023],axis=0)
print("Before=%d"%(matching_continets_per_country.shape[0]))
matching_continets_per_country.drop_duplicates(inplace=True, keep="first")
print("After=%d"%(matching_continets_per_country.shape[0]))

Before=57620
After=98

In [34]:
data_2025 = data_2025.rename({"nome_pais_correto":"País"}, axis='columns')
data_2025.head()

  Via_de_acesso              UF         País      mes   ano  Chegadas
0         Aérea  Rio de Janeiro  Afeganistão  Janeiro  2025         1
1         Aérea       São Paulo  Afeganistão  Janeiro  2025         3
2     Terrestre          Paraná  Afeganistão  Janeiro  2025         2
3     Terrestre  Santa Catarina  Afeganistão  Janeiro  2025         4
4     Terrestre  Santa Catarina  Afeganistão  Janeiro  2025         2

In [37]:
matching_continets_per_country[matching_continets_per_country["País"].duplicated(keep=False)]

                    Continente           País
2                         Ásia  Outros países
48                      Europa  Outros países
125                     África  Outros países
207   América Central e Caribe  Outros países
4299                   Oceania  Outros países

In [39]:
matching_continets_per_country.drop(matching_continets_per_country[matching_continets_per_country["País"] == "Outros países"].index, inplace=True)

In [40]:
matching_continets_per_country[matching_continets_per_country["País"].duplicated(keep=False)]

Empty DataFrame
Columns: [Continente, País]
Index: []

In [41]:
data_2025["Continente"] = data_2025["País"].map(matching_continets_per_country.set_index('País')['Continente'])
data_2025.head()

,Via_de_acesso,UF,País,mes,ano,Chegadas,Continente
0,Aérea,Rio de Janeiro,Afeganistão,Janeiro,2025,1,NaN
1,Aérea,São Paulo,Afeganistão,Janeiro,2025,3,NaN
2,Terrestre,Paraná,Afeganistão,Janeiro,2025,2,NaN
3,Terrestre,Santa Catarina,Afeganistão,Janeiro,2025,4,NaN
4,Terrestre,Santa Catarina,Afeganistão,Janeiro,2025,2,NaN

In [49]:
data_2025["País"].nunique(), ["País"].nunique()

(201, 86)

In [52]:
matching_continets_per_country[matching_continets_per_country["País"] == "Afeganistão"]

Empty DataFrame
Columns: [Continente, País]
Index: []

In [54]:
data_2025[~data_2025["País"].isin(matching_continets_per_country["País"])]["País"].unique()

array(['Afeganistão', 'Albânia', 'Andorra', 'Antilhas Holandesas',
       'Antígua e Barbuda', 'Argélia', 'Armênia', 'Azerbaijão', 'Bahamas',
       'Barbados', 'Barein', 'Belize', 'Benin', 'Bielorússia', 'Botsuana',
       'Burkina Faso', 'Burundi', 'Butão', 'Bélgica',
       'Bósnia-Herzegovina', 'Camarões', 'Camboja', 'Casaquistão',
       'Catar', 'Chade', 'China, Macao', 'Chipre', 'Congo',
       'Costa do Marfim', 'Dominica', 'Emirados Árabes Unidos',
       'Eritréia', 'Etiópia', 'Fiji', 'Gabão', 'Geórgia', 'Granada',
       'Guiné', 'Guiné Equatorial', 'Guiné-Bissau', 'Gâmbia', 'Honduras',
       'Iraque', 'Islândia', 'Iêmen', 'Jamaica', 'Jordânia', 'Kuwait',
       'Libéria', 'Liechtenstein', 'Líbia', 'Macedônia', 'Madagascar',
       'Malauí', 'Maldivas', 'Mali', 'Malta', 'Mauritânia', 'Maurício',
       'Mianma', 'Moldávia', 'Mongólia', 'Montenegro', 'Mônaco',
       'Namíbia', 'Nepal', 'Omã', 'Palestina', 'Papua Nova Guiné',
       'Porto Rico', 'Quirguistão', 'República Centro Africana',
       'República Democrática do Congo', 'República do Kosovo', 'Ruanda',
       'Samoa', 'San Marino', 'Santa Lúcia', 'Seichelles', 'Senegal',
       'Serra Leoa', 'Somália', 'Sri Lanka', 'Sudão',
       'São Cristóvão e Nevis', 'São Tome e Príncipe', 'Tanzânia',
       'Timor Leste', 'Togo', 'Turcomenistão', 'Uganda', 'Uzbequistão',
       'Vietnã', 'Zimbábue', 'Zâmbia', 'Sudão do Sul',
       'São Vicente e Granadinas', 'Tadjiquistão', 'Vanuatu', 'Brunei',
       'Comores', 'Coreia do Norte', 'Laos', 'Lesoto', 'Níger',
       'Suazilândia', 'Tonga', 'Djibouti', 'Ilhas Salomão', 'Kiribati',
       'Nauru', 'Tuvalu', 'Vaticano', 'Micronésia', 'Palau'], dtype=object)

In [ ]:
https://www.countrydataapi.com/pt/docs
https://github.com/LibreTranslate/LibreTranslate
https://libretranslate.com/

In [42]:
data_2025["Continente"].unique()

array([nan, 'Europa', 'África', 'América do Sul', 'Ásia', 'Oceania',
       'América do Norte', 'América Central e Caribe',
       'Continente não especificado'], dtype=object)

In [68]:
paises = pd.DataFrame(columns=["2023", "2024", "2025"])
paises["2023"] = paises_2023
paises["2024"] = paises_2024
paises["2025"] = paises_2025
paises.head()

              2023                  2024                    2025
2         Alemanha               Bélgica                Alemanha
51          Angola  República Dominicana  Emirados Árabes Unidos
3        Argentina                Canadá                 Andorra
52  Arábia Saudita      República Tcheca                 Equador
4        Austrália                 Chile                  Angola

In [58]:
columns_to_drop = ["cod uf", "cod continente", "cod mes", "cod pais", "cod via"]
rename_columns = {"Via_de_acesso":"Via", "nome_pais_correto":"País"}

data = pd.DataFrame()

for csv_file in csv_files:
    file = pd.read_csv(csv_file, encoding="windows-1252", sep=";")

    try:
        file.drop(columns_to_drop,inplace=True,axis=1)
    except KeyError:
        pass

    file.rename(rename_columns,inplace=True,axis="columns")

    print("%d file has rows=%d; columns=%d"%(year, file.shape[0], file.shape[1]))
    print("columns=%s\n"%(str(file.columns)))
    
    data = pd.concat([data,file],axis=0)
    del file
    gc.collect()

print("all_data file has rows=%d; columns=%d"%(data.shape[0], data.shape[1])) 
print("columns=%s"%(str(data.columns)))
data.to_csv("all_data.csv",index=False)

2024 file has rows=16271; columns=6
columns=Index(['Via', 'UF', 'País', 'mes', 'ano', 'Chegadas'], dtype='object')

2024 file has rows=34764; columns=7
columns=Index(['Continente', 'País', 'UF', 'Via', 'ano', 'Mês', 'Chegadas'], dtype='object')

2024 file has rows=22856; columns=7
columns=Index(['Continente', 'País', 'UF', 'Via', 'ano', 'Mês', 'Chegadas'], dtype='object')

all_data file has rows=73891; columns=8
columns=Index(['Via', 'UF', 'País', 'mes', 'ano', 'Chegadas', 'Continente', 'Mês'], dtype='object')