In [7]:
%pip install summarytools scipy openpyxl --break-system-packages

Requirement already satisfied: summarytools in /usr/lib/python3.13/site-packages (0.3.0)
Requirement already satisfied: scipy in /usr/lib/python3.13/site-packages (1.16.1)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pandas>=1.4.0 in /usr/lib/python3.13/site-packages (from summarytools) (2.3.2)
Requirement already satisfied: ipython>=7.20.0 in /usr/lib/python3.13/site-packages (from summarytools) (9.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/lib/python3.13/site-packages (from summarytools) (2.3.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/lib/python3.13/site-packages (from summarytools) (3.10.5)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: decorator in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (0.19.2)
Requirement already satisfied: matplotlib-inline in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (2.19.2)
Requirement already satisfied: stack_data in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /usr/lib/python3.13/site-packages (from ipython>=7.20.0->summarytools) (5.14.3)
Requirement already satisfied: wcwidth in /usr/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.20.0->summarytools) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/lib/python3.13/site-packages (from jedi>=0.16->ipython>=7.20.0->summarytools) (0.8.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (25.0)
Requirement already satisfied: pillow>=8 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3.13/site-packages (from matplotlib>=3.3.0->summarytools) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.13/site-packages (from pandas>=1.4.0->summarytools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/lib/python3.13/site-packages (from pandas>=1.4.0->summarytools) (2025.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.13/site-packages (from pexpect>4.3->ipython>=7.20.0->summarytools) (0.7.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->summarytools) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /usr/lib/python3.13/site-packages (from stack_data->ipython>=7.20.0->summarytools) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /usr/lib/python3.13/site-packages (from stack_data->ipython>=7.20.0->summarytools) (3.0.0)
Requirement already satisfied: pure-eval in /usr/lib/python3.13/site-packages (from stack_data->ipython>=7.20.0->summarytools) (0.2.3)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import seaborn as sns
import summarytools as st
from summarytools import dfSummary
import matplotlib.pyplot as plt
import scipy.stats as stats

In [12]:
df = pd.read_excel("Banco.xlsx")
df.head()

,id,idade,sexo,sexo_cliente,estudo,produto_categorizado,produto,salario,salarin,temp_ser,cartao_credito,emprestimos
0,459,18,Feminino,1,12,C,3,21750,11250.0,65,4350,2175.0
1,459,18,Feminino,1,12,C,3,21750,11250.0,65,4350,2175.0
2,439,18,Feminino,1,12,C,3,20400,11250.0,66,4080,2040.0
3,399,18,Feminino,1,12,C,3,20400,11250.0,69,4080,2040.0
4,398,18,Feminino,1,12,C,3,30600,12450.0,69,6120,3060.0

In [17]:
def contar_valores_percentual(data):
    variaveis_object = data.select_dtypes(include=["object"]).columns

    tabelas = []
    for column in variaveis_object:
        tabela_tmp = data[column].value_counts(normalize=False).reset_index()
        tabela_tmp.columns = ["Valor", "Contagem"]
        tabela_tmp["Percentual"] = (data[column].value_counts(normalize=True).values * 100).round(2)
        tabela_tmp["Variavel"]=column
        tabelas.append(tabela_tmp)
    resultado = pd.concat(tabelas, ignore_index=True)
    return resultado[["Variavel", "Valor", "Contagem", "Percentual"]]

In [18]:
contar_valores_percentual(df)

               Variavel      Valor  Contagem  Percentual
0                  sexo  Masculino       278       54.30
1                  sexo   Feminino       234       45.70
2  produto_categorizado          C       391       76.37
3  produto_categorizado          A        94       18.36
4  produto_categorizado          B        27        5.27

In [19]:
df.describe().estudo

count    512.000000
mean      13.552734
std        2.890898
min        8.000000
25%       12.000000
50%       12.000000
75%       15.000000
max       21.000000
Name: estudo, dtype: float64

In [20]:
bins = [
    df["estudo"].min(),
    df["estudo"].quantile(0.2),
    df["estudo"].quantile(0.6),
    df["estudo"].quantile(0.8),
    df["estudo"].max(),
]

grupos = ["Graduacao","Mestrado","Doutorado", "Pos-Doutorado"]

df["faixa_estudo"]=pd.cut(df["estudo"],bins=bins,labels=grupos, include_lowest=True, duplicates="drop")

df["faixa_estudo"].value_counts()

faixa_estudo
Graduacao        259
Mestrado         133
Doutorado         63
Pos-Doutorado     57
Name: count, dtype: int64

In [30]:
df[df.estudo == 14]

,id,idade,sexo,sexo_cliente,estudo,produto_categorizado,produto,salario,salarin,temp_ser,cartao_credito,emprestimos,faixa_estudo
113,369,19,Masculino,2,14,C,3,28050,15000.0,71,5610,2805.0,Mestrado
142,282,19,Masculino,2,14,C,3,27900,15000.0,79,5580,2790.0,Mestrado
159,388,19,Masculino,2,14,C,3,30150,16500.0,69,6030,3015.0,Mestrado
339,102,36,Masculino,2,14,C,3,39900,15750.0,91,7980,3990.0,Mestrado
395,114,38,Masculino,2,14,C,3,37800,16500.0,90,7560,3780.0,Mestrado
511,292,58,Masculino,2,14,C,3,25950,15000.0,78,5190,2595.0,Mestrado

In [32]:
df[df.estudo == 16]

,id,idade,sexo,sexo_cliente,estudo,produto_categorizado,produto,salario,salarin,temp_ser,cartao_credito,emprestimos,faixa_estudo
110,467,19,Feminino,1,16,C,3,32850,19500.0,64,6570,3285.0,Doutorado
120,468,23,Feminino,1,16,A,1,55750,19980.0,64,11150,5575.0,Doutorado
128,468,24,Feminino,1,16,A,1,55750,19980.0,64,11150,5575.0,Doutorado
133,455,24,Masculino,2,16,A,1,43650,19500.0,65,8730,4365.0,Doutorado
145,266,19,Feminino,1,16,C,3,34500,17250.0,80,6900,3450.0,Doutorado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,426,47,Masculino,2,16,C,3,33300,17490.0,67,6660,3330.0,Doutorado
471,160,48,Masculino,2,16,A,1,66000,47490.0,86,13200,6600.0,Doutorado
472,159,48,Feminino,1,16,C,3,25050,12750.0,87,5010,2505.0,Doutorado
480,11,49,Feminino,1,16,C,3,30300,16500.0,98,6060,3030.0,Doutorado
483,217,50,Masculino,2,16,C,3,34620,27750.0,82,6924,3462.0,Doutorado

In [25]:
df.estudo.unique()

array([12, 15,  8, 17, 21, 16, 14, 19, 18, 20])

In [29]:
df.estudo.min(), df.estudo.quantile(0.2), df.estudo.quantile(0.6)

(np.int64(8), np.float64(12.0), np.float64(15.0))

In [26]:
df.estudo.quantile(0.2)

np.float64(12.0)

In [23]:
df.tail(10)

,id,idade,sexo,sexo_cliente,estudo,produto_categorizado,produto,salario,salarin,temp_ser,cartao_credito,emprestimos,faixa_estudo
502,82,52,Feminino,1,12,C,3,24750,14250.0,93,4950,2475.0,Graduacao
503,48,52,Masculino,2,12,B,2,30750,14100.0,94,6150,3075.0,Graduacao
504,4,52,Feminino,1,8,C,3,21900,13200.0,98,4380,2190.0,Graduacao
505,429,53,Masculino,2,8,B,2,30000,15750.0,67,6000,3000.0,Graduacao
506,381,53,Masculino,2,17,C,3,27000,18000.0,70,5400,2700.0,Pos-Doutorado
507,354,53,Feminino,1,12,C,3,20550,11250.0,73,4110,2055.0,Graduacao
508,344,58,Masculino,2,12,C,3,35700,16500.0,73,7140,3570.0,Graduacao
509,312,58,Feminino,1,12,C,3,25650,14250.0,77,5130,2565.0,Graduacao
510,308,58,Masculino,2,15,C,3,34500,18000.0,77,6900,3450.0,Mestrado
511,292,58,Masculino,2,14,C,3,25950,15000.0,78,5190,2595.0,Mestrado

In [33]:
df["faixa_estudo"] = df["faixa_estudo"].replace({"Doutorado":"Outros", "Pos-Doutorado":"Outros"})
df["faixa_estudo"].value_counts()

/tmp/ipykernel_3441/2922461674.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["faixa_estudo"] = df["faixa_estudo"].replace({"Doutorado":"Outros", "Pos-Doutorado":"Outros"})

faixa_estudo
Graduacao    259
Mestrado     133
Outros       120
Name: count, dtype: int64

In [34]:
faixa_estudo_counts = df["faixa_estudo"].value_counts()
faixa_estudo_percentual = df["faixa_estudo"].value_counts(normalize=True)*100

In [11]:
dfSummary(df, is_collapsible=True)