In [1]:
!pip install pandas mlxtend pyECLAT --break-system-packages

Requirement already satisfied: pandas in /usr/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: mlxtend in /usr/lib/python3.13/site-packages (0.23.4)
Requirement already satisfied: pyECLAT in /usr/lib/python3.13/site-packages (1.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/lib/python3.13/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.13/site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/lib/python3.13/site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/lib/python3.13/site-packages (from mlxtend) (1.7.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/lib/python3.13/site-packages (from mlxtend) (3.10.7)
Requirement already satisfied: joblib>=0.13.2 in /usr/lib/python3.13/site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/lib/python3.13/site-packages (from pyECLAT) (4.67.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in /usr/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /usr/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/lib/python3.13/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from pyECLAT import ECLAT

In [3]:
dataset = "https://raw.githubusercontent.com/yashuv/CodeClause_Market_Basket_Analysis_in_Python_using_Apriori_Algorithm/refs/heads/main/data/Groceries_dataset.csv"

In [4]:
data = pd.read_csv(dataset)
data.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [5]:
data.drop("Date",axis=1,inplace=True)

In [6]:
data["itemDescription"].nunique()

167

In [7]:
data[data["Member_number"] == 1808].groupby(["Member_number","itemDescription"])["itemDescription"].count()

Member_number  itemDescription
1808           candy                       1
               citrus fruit                1
               long life bakery product    1
               meat                        1
               napkins                     1
               rolls/buns                  1
               semi-finished bread         1
               sugar                       1
               tropical fruit              1
               whole milk                  1
Name: itemDescription, dtype: int64

In [8]:
all_data_grouped = data.groupby(["Member_number","itemDescription"])["itemDescription"].count().unstack().reset_index().fillna(0).set_index("Member_number")
all_data_grouped.head()

itemDescription,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
Member_number,,,,,,,,,,,,,,,,,,,,,
1000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0
1001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0
1002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0

In [9]:
def fix_values(x):
    return 0 if x <= 0 else 1

In [10]:
all_data_grouped = all_data_grouped.map(fix_values)

In [11]:
all_data_grouped.head()

itemDescription,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
Member_number,,,,,,,,,,,,,,,,,,,,,
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1001,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,1,0,0
1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [12]:
algo = apriori(all_data_grouped, min_support=0.06, use_colnames=True)
rules = association_rules(algo, metric="lift", min_threshold=1)
rules.sort_values(["lift", "support"]).head(10)

/usr/lib/python3.13/site-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
62,(tropical fruit),(other vegetables),0.233710,0.376603,0.091329,0.390779,1.037642,1.0,0.003313,1.023269,0.047340,0.175976,0.022740,0.316643
63,(other vegetables),(tropical fruit),0.376603,0.233710,0.091329,0.242507,1.037642,1.0,0.003313,1.011614,0.058191,0.175976,0.011480,0.316643
60,(soda),(other vegetables),0.313494,0.376603,0.124166,0.396072,1.051695,1.0,0.006103,1.032237,0.071601,0.219402,0.031230,0.362886
61,(other vegetables),(soda),0.376603,0.313494,0.124166,0.329700,1.051695,1.0,0.006103,1.024178,0.078849,0.219402,0.023607,0.362886
117,(whole milk),(soda),0.458184,0.313494,0.151103,0.329787,1.051973,1.0,0.007465,1.024310,0.091184,0.243489,0.023733,0.405892
116,(soda),(whole milk),0.313494,0.458184,0.151103,0.481997,1.051973,1.0,0.007465,1.045971,0.071966,0.243489,0.043950,0.405892
10,(rolls/buns),(bottled water),0.349666,0.213699,0.079271,0.226706,1.060863,1.0,0.004548,1.016820,0.088219,0.163752,0.016541,0.298827
11,(bottled water),(rolls/buns),0.213699,0.349666,0.079271,0.370948,1.060863,1.0,0.004548,1.033832,0.072964,0.163752,0.032725,0.298827
48,(pastry),(other vegetables),0.177527,0.376603,0.071575,0.403179,1.070567,1.0,0.004718,1.044529,0.080143,0.148325,0.042631,0.296617
49,(other vegetables),(pastry),0.376603,0.177527,0.071575,0.190054,1.070567,1.0,0.004718,1.015467,0.105736,0.148325,0.015232,0.296617

In [13]:
data = pd.read_csv(dataset)

In [14]:
grouped = data.groupby(["Member_number","Date"])["itemDescription"].apply(list).reset_index()
transactions = grouped["itemDescription"].tolist()
transactions

[['sausage', 'whole milk', 'semi-finished bread', 'yogurt'],
 ['whole milk', 'pastry', 'salty snack'],
 ['canned beer', 'misc. beverages'],
 ['sausage', 'hygiene articles'],
 ['soda', 'pickled vegetables'],
 ['frankfurter', 'curd'],
 ['sausage', 'whole milk', 'rolls/buns'],
 ['whole milk', 'soda'],
 ['beef', 'white bread'],
 ['frankfurter', 'soda', 'whipped/sour cream'],
 ['frozen vegetables', 'other vegetables'],
 ['butter', 'whole milk'],
 ['tropical fruit', 'sugar'],
 ['butter milk', 'specialty chocolate'],
 ['sausage', 'rolls/buns'],
 ['root vegetables', 'detergent'],
 ['frozen meals', 'dental care'],
 ['rolls/buns', 'rolls/buns'],
 ['dish cleaner', 'cling film/bags'],
 ['canned beer', 'frozen fish'],
 ['other vegetables', 'hygiene articles'],
 ['pip fruit', 'whole milk', 'tropical fruit'],
 ['rolls/buns', 'red/blush wine', 'chocolate'],
 ['other vegetables', 'shopping bags'],
 ['whole milk', 'chocolate', 'packaged fruit/vegetables', 'rolls/buns'],
 ['root vegetables', 'whole milk', 'pastry'],
 ['rolls/buns', 'rolls/buns'],
 ['whipped/sour cream', 'margarine'],
 ['bottled water', 'softener', 'rolls/buns'],
 ['whole milk', 'rice'],
 ['shopping bags', 'skin care'],
 ['whole milk',
  'frankfurter',
  'chicken',
  'frankfurter',
  'flour',
  'chocolate',
  'bottled beer',
  'rolls/buns'],
 ['hamburger meat', 'liquor (appetizer)', 'liver loaf', 'dessert'],
 ['tropical fruit',
  'soda',
  'yogurt',
  'root vegetables',
  'yogurt',
  'domestic eggs',
  'white wine',
  'photo/film'],
 ['herbs', 'yogurt', 'newspapers'],
 ['tropical fruit', 'yogurt'],
 ['pastry', 'ketchup'],
 ['canned fish', 'cocoa drinks'],
 ['pip fruit', 'coffee', 'UHT-milk'],
 ['kitchen towels', 'sliced cheese'],
 ['bottled water', 'specialty bar'],
 ['frankfurter', 'bottled water'],
 ['pip fruit', 'candles', 'rolls/buns'],
 ['curd cheese', 'pastry'],
 ['whole milk',
  'frankfurter',
  'candles',
  'grapes',
  'herbs',
  'other vegetables',
  'yogurt'],
 ['citrus fruit', 'candy', 'bottled water', 'rolls/buns'],
 ['frankfurter', 'yogurt'],
 ['tropical fruit',
  'root vegetables',
  'rolls/buns',
  'onions',
  'shopping bags'],
 ['frozen vegetables', 'brown bread'],
 ['processed cheese', 'whole milk'],
 ['frozen meals', 'whole milk'],
 ['white bread', 'meat', 'domestic eggs', 'roll products '],
 ['root vegetables', 'mayonnaise'],
 ['other vegetables', 'mustard'],
 ['hard cheese', 'napkins', 'bottled water'],
 ['whole milk', 'candy'],
 ['tropical fruit', 'frozen vegetables'],
 ['mustard', 'whipped/sour cream'],
 ['whole milk', 'sausage', 'bottled beer', 'yogurt'],
 ['canned beer', 'cookware'],
 ['hamburger meat', 'butter milk'],
 ['whole milk', 'rolls/buns'],
 ['citrus fruit', 'whole milk'],
 ['salty snack', 'beef'],
 ['fruit/vegetable juice', 'rolls/buns', 'chocolate'],
 ['UHT-milk', 'bottled beer'],
 ['chicken', 'red/blush wine'],
 ['soft cheese', 'pip fruit'],
 ['rolls/buns', 'frankfurter', 'oil', 'pip fruit', 'mayonnaise'],
 ['brown bread', 'pet care'],
 ['other vegetables', 'rolls/buns'],
 ['yogurt', 'beef'],
 ['other vegetables', 'root vegetables'],
 ['soda', 'dessert', 'shopping bags'],
 ['curd', 'long life bakery product'],
 ['beverages', 'domestic eggs'],
 ['butter milk', 'root vegetables'],
 ['berries', 'cake bar'],
 ['hamburger meat', 'red/blush wine'],
 ['canned beer', 'shopping bags'],
 ['canned beer', 'spices', 'rolls/buns', 'frozen fish'],
 ['frozen meals', 'butter', 'newspapers', 'yogurt'],
 ['rolls/buns', 'baking powder'],
 ['liquor', 'curd', 'yogurt', 'tropical fruit'],
 ['sliced cheese', 'butter'],
 ['sausage', 'fruit/vegetable juice'],
 ['beef', 'napkins'],
 ['whole milk', 'whipped/sour cream'],
 ['whipped/sour cream',
  'root vegetables',
  'rolls/buns',
  'packaged fruit/vegetables'],
 ['domestic eggs', 'soda'],
 ['chicken', 'frozen meals'],
 ['male cosmetics', 'curd'],
 ['white bread', 'bottled beer', 'yogurt', 'berries'],
 ['sausage', 'whipped/sour cream', 'specialty bar'],
 ['fish', 'root vegetables', 'tropical fruit', 'other vegetables'],
 ['coffee', 'shopping bags'],
 ['ham', 'cream cheese '],
 ['canned beer', 'UHT-milk'],
 ['sausage', 'dessert', 'rolls/buns', 'pickled vegetables'],
 ['fruit/vegetable juice', 'salty snack', 'candy', 'dental care', 'butter'],
 ['root vegetables', 'long life bakery product'],
 ['citrus fruit', 'yogurt'],
 ['root vegetables', 'whipped/sour cream', 'root vegetables', 'canned beer'],
 ['softener', 'salt', 'whole milk'],
 ['pork', 'hamburger meat'],
 ['rolls/buns', 'bottled water'],
 ['rolls/buns', 'red/blush wine'],
 ['onions', 'canned beer', 'flower (seeds)'],
 ['rolls/buns', 'sugar'],
 ['soda', 'butter'],
 ['specialty chocolate', 'root vegetables'],
 ['rolls/buns', 'baking powder', 'onions', 'bottled water'],
 ['dessert', 'ham'],
 ['ice cream', 'pot plants'],
 ['other vegetables', 'other vegetables', 'berries'],
 ['beverages', 'cream cheese '],
 ['ice cream', 'whipped/sour cream'],
 ['berries',
  'soda',
  'butter',
  'other vegetables',
  'white bread',
  'cream cheese '],
 ['yogurt', 'root vegetables'],
 ['white bread', 'whole milk', 'pastry', 'shopping bags'],
 ['whipped/sour cream', 'newspapers'],
 ['frankfurter', 'pastry'],
 ['chicken', 'waffles'],
 ['fruit/vegetable juice', 'dessert'],
 ['sausage', 'snack products', 'rolls/buns'],
 ['tropical fruit', 'soda', 'rolls/buns'],
 ['tropical fruit', 'newspapers'],
 ['pip fruit', 'cling film/bags', 'yogurt', 'cat food'],
 ['bottled water', 'domestic eggs', 'frozen meals'],
 ['whole milk', 'newspapers'],
 ['pip fruit', 'white wine', 'white bread', 'salt'],
 ['sausage', 'frozen vegetables'],
 ['whole milk', 'yogurt', 'yogurt', 'rolls/buns'],
 ['whole milk', 'frozen vegetables'],
 ['fruit/vegetable juice', 'vinegar'],
 ['citrus fruit', 'shopping bags', 'chewing gum', 'cake bar'],
 ['frankfurter', 'yogurt', 'canned beer'],
 ['tropical fruit', 'white bread', 'rolls/buns'],
 ['whole milk', 'pip fruit', 'whipped/sour cream'],
 ['other vegetables', 'specialty chocolate'],
 ['Instant food products', 'whipped/sour cream', 'butter', 'cake bar'],
 ['sausage', 'pork', 'butter', 'whole milk', 'fruit/vegetable juice'],
 ['pip fruit', 'herbs', 'frozen meals'],
 ['margarine', 'napkins'],
 ['salty snack', 'rolls/buns'],
 ['whole milk', 'pasta', 'rolls/buns'],
 ['yogurt', 'rolls/buns'],
 ['root vegetables', 'white bread'],
 ['tropical fruit', 'chicken', 'onions', 'packaged fruit/vegetables'],
 ['hamburger meat', 'yogurt'],
 ['prosecco', 'dessert'],
 ['chicken', 'frozen vegetables', 'candy'],
 ['tropical fruit', 'brown bread', 'whole milk'],
 ['beef', 'dessert'],
 ['whole milk', 'other vegetables'],
 ['citrus fruit', 'bottled water'],
 ['citrus fruit', 'rolls/buns', 'whole milk'],
 ['tropical fruit', 'sliced cheese'],
 ['napkins', 'whole milk', 'chocolate marshmallow'],
 ['tropical fruit', 'other vegetables'],
 ['root vegetables', 'curd'],
 ['fruit/vegetable juice', 'specialty chocolate', 'Instant food products'],
 ['root vegetables', 'yogurt', 'butter', 'yogurt'],
 ['chicken', 'onions'],
 ['whole milk', 'pastry'],
 ['pork', 'bottled water'],
 ['curd', 'soda'],
 ['sweet spreads', 'butter'],
 ['pip fruit', 'soda'],
 ['rolls/buns', 'condensed milk', 'whole milk', 'soda'],
 ['rolls/buns', 'tropical fruit'],
 ['butter', 'whole milk'],
 ['white bread', 'candy'],
 ['frankfurter', 'herbs'],
 ['specialty bar', 'margarine'],
 ['meat', 'whole milk'],
 ['house keeping products', 'yogurt'],
 ['whipped/sour cream', 'hygiene articles'],
 ['UHT-milk', 'other vegetables', 'dishes'],
 ['waffles', 'beverages'],
 ['pasta', 'yogurt', 'cat food'],
 ['fish', 'tropical fruit', 'red/blush wine', 'cream cheese '],
 ['other vegetables', 'soda', 'rolls/buns', 'dishes'],
 ['tropical fruit',
  'other vegetables',
  'hamburger meat',
  'popcorn',
  'female sanitary products'],
 ['hamburger meat', 'bottled beer'],
 ['pork', 'coffee', 'frozen vegetables'],
 ['shopping bags', 'shopping bags'],
 ['beef', 'shopping bags'],
 ['soda', 'hamburger meat'],
 ['butter milk', 'yogurt', 'yogurt', 'margarine'],
 ['soda', 'whole milk'],
 ['root vegetables', 'grapes'],
 ['frankfurter', 'whipped/sour cream'],
 ['bottled water', 'chewing gum'],
 ['chicken', 'beverages', 'coffee'],
 ['pork',
  'other vegetables',
  'yogurt',
  'shopping bags',
  'soft cheese',
  'detergent'],
 ['butter', 'dog food'],
 ['chicken', 'frozen vegetables'],
 ['hamburger meat', 'pastry'],
 ['other vegetables', 'whole milk'],
 ['waffles', 'rolls/buns'],
 ['whole milk', 'sugar'],
 ['soda', 'soda'],
 ['bottled beer', 'oil'],
 ['frankfurter', 'citrus fruit', 'margarine'],
 ['soda', 'fruit/vegetable juice'],
 ['photo/film', 'other vegetables'],
 ['pork', 'white wine'],
 ['bottled water', 'yogurt', 'newspapers', 'soda'],
 ['whipped/sour cream', 'meat spreads'],
 ['pip fruit', 'other vegetables'],
 ['ham', 'whole milk'],
 ['salty snack', 'pickled vegetables'],
 ['soda', 'domestic eggs', 'sliced cheese', 'soda'],
 ['tropical fruit', 'UHT-milk'],
 ['sausage', 'bottled water'],
 ['yogurt', 'root vegetables'],
 ['root vegetables', 'other vegetables'],
 ['chicken', 'other vegetables'],
 ['dessert', 'spread cheese'],
 ['sausage', 'salty snack', 'cling film/bags'],
 ['whole milk',
  'tropical fruit',
  'root vegetables',
  'Instant food products',
  'margarine'],
 ['soda', 'fruit/vegetable juice', 'bottled beer'],
 ['beef', 'chocolate'],
 ['beverages', 'dessert'],
 ['whipped/sour cream', 'hard cheese'],
 ['ham', 'whipped/sour cream', 'ketchup'],
 ['white bread', 'frozen fruits'],
 ['tropical fruit',
  'whole milk',
  'other vegetables',
  'long life bakery product'],
 ['other vegetables', 'yogurt', 'whole milk', 'butter', 'shopping bags'],
 ['whole milk', 'sauces'],
 ['whole milk', 'citrus fruit'],
 ['rolls/buns', 'candy'],
 ['root vegetables', 'whole milk'],
 ['cream cheese ', 'rolls/buns'],
 ['long life bakery product', 'root vegetables', 'other vegetables'],
 ['tropical fruit', 'rolls/buns'],
 ['frankfurter', 'tropical fruit'],
 ['tropical fruit', 'whole milk', 'long life bakery product', 'rum'],
 ['hamburger meat', 'soda'],
 ['red/blush wine', 'frozen fish'],
 ['beef', 'dessert'],
 ['root vegetables', 'bottled beer'],
 ['oil', 'shopping bags'],
 ['whole milk', 'other vegetables'],
 ['whole milk', 'tropical fruit'],
 ['hamburger meat', 'pork'],
 ['rolls/buns', 'tropical fruit', 'coffee', 'chocolate'],
 ['pork', 'spread cheese'],
 ['soda', 'yogurt'],
 ['salt', 'domestic eggs'],
 ['pork', 'rolls/buns'],
 ['brown bread', 'fruit/vegetable juice'],
 ['bottled beer', 'tropical fruit', 'sliced cheese', 'dishes'],
 ['cream cheese ', 'newspapers'],
 ['citrus fruit', 'red/blush wine'],
 ['yogurt', 'roll products ', 'fruit/vegetable juice'],
 ['ham', 'other vegetables'],
 ['frankfurter', 'canned beer'],
 ['finished products', 'brown bread', 'dishes'],
 ['yogurt', 'bottled water', 'domestic eggs'],
 ['pip fruit', 'curd', 'pip fruit', 'prosecco'],
 ['brown bread', 'salt'],
 ['semi-finished bread', 'ketchup'],
 ['oil', 'shopping bags'],
 ['fruit/vegetable juice', 'flower (seeds)'],
 ['misc. beverages', 'instant coffee'],
 ['detergent', 'candy'],
 ['UHT-milk', 'canned fish'],
 ['frankfurter', 'citrus fruit', 'bottled water', 'fruit/vegetable juice'],
 ['frankfurter', 'frozen meals', 'dishes'],
 ['pip fruit', 'rolls/buns'],
 ['sausage', 'butter', 'bottled water'],
 ['frankfurter', 'chicken', 'butter', 'bottled water'],
 ['ham', 'whole milk', 'whole milk', 'coffee'],
 ['sausage', 'brown bread'],
 ['other vegetables', 'butter'],
 ['tropical fruit', 'soda'],
 ['pastry', 'pasta'],
 ['white bread', 'brown bread'],
 ['canned beer', 'rolls/buns', 'artif. sweetener', 'soda'],
 ['rolls/buns', 'root vegetables'],
 ['chicken', 'soda'],
 ['frankfurter', 'curd', 'white bread', 'rolls/buns', 'coffee'],
 ['red/blush wine', 'bottled water', 'sweet spreads'],
 ['rolls/buns', 'onions', 'napkins'],
 ['canned beer', 'soda'],
 ['root vegetables', 'frozen vegetables', 'pet care'],
 ['specialty bar',
  'tropical fruit',
  'yogurt',
  'bottled beer',
  'baking powder'],
 ['other vegetables', 'frankfurter', 'newspapers', 'whole milk', 'pastry'],
 ['beverages', 'yogurt'],
 ['tropical fruit', 'whole milk'],
 ['coffee', 'butter milk'],
 ['beef', 'margarine', 'other vegetables'],
 ['bottled water', 'hygiene articles'],
 ['pork', 'sliced cheese'],
 ['specialty chocolate', 'soda', 'bathroom cleaner'],
 ['hamburger meat', 'whole milk'],
 ['pip fruit', 'other vegetables'],
 ['root vegetables', 'citrus fruit'],
 ['other vegetables', 'shopping bags', 'soda'],
 ['yogurt', 'newspapers'],
 ['ice cream', 'whipped/sour cream'],
 ['other vegetables', 'beef', 'soda', 'curd', 'butter'],
 ['canned beer', 'herbs', 'margarine'],
 ['rolls/buns', 'soda'],
 ['rolls/buns', 'citrus fruit'],
 ['coffee', 'berries'],
 ['ham', 'white bread'],
 ['herbs', 'pot plants', 'cake bar'],
 ['soda', 'flower (seeds)', 'jam'],
 ['sausage', 'pip fruit', 'chocolate'],
 ['specialty chocolate', 'white bread'],
 ['whole milk', 'whole milk'],
 ['other vegetables', 'whole milk'],
 ['sausage', 'beverages'],
 ['whole milk', 'hard cheese'],
 ['yogurt', 'berries'],
 ['tropical fruit',
  'meat',
  'other vegetables',
  'domestic eggs',
  'baking powder'],
 ['yogurt', 'sauces'],
 ['beef', 'yogurt'],
 ['ice cream', 'whole milk'],
 ['sausage',
  'whisky',
  'specialty chocolate',
  'dishes',
  'yogurt',
  'napkins',
  'detergent',
  'pastry'],
 ['photo/film', 'shopping bags'],
 ['frankfurter', 'other vegetables', 'bottled beer'],
 ['yogurt', 'newspapers'],
 ['root vegetables',
  'soda',
  'specialty bar',
  'other vegetables',
  'frozen vegetables'],
 ['rolls/buns',
  'grapes',
  'bottled beer',
  'sausage',
  'salty snack',
  'Instant food products',
  'domestic eggs',
  'bottled water'],
 ['dessert', 'domestic eggs'],
 ['sausage', 'tropical fruit', 'misc. beverages', 'root vegetables'],
 ['sausage', 'whole milk'],
 ['whole milk', 'brown bread'],
 ['hamburger meat', 'detergent', 'flour'],
 ['tropical fruit', 'soda'],
 ['newspapers', 'salty snack'],
 ['pasta', 'whole milk', 'waffles'],
 ['chocolate marshmallow', 'other vegetables'],
 ['pickled vegetables', 'flour'],
 ['yogurt', 'shopping bags'],
 ['packaged fruit/vegetables', 'bottled water', 'pork', 'domestic eggs'],
 ['pip fruit', 'fruit/vegetable juice'],
 ['tropical fruit', 'whole milk', 'soda', 'curd'],
 ['shopping bags', 'root vegetables'],
 ['whipped/sour cream', 'curd', 'shopping bags'],
 ['sausage', 'whole milk', 'cake bar'],
 ['frankfurter', 'whipped/sour cream', 'bottled water'],
 ['hard cheese', 'whole milk'],
 ['tropical fruit',
  'citrus fruit',
  'yogurt',
  'frankfurter',
  'specialty chocolate',
  'hard cheese',
  'whole milk',
  'canned beer'],
 ['canned beer', 'napkins', 'rolls/buns'],
 ['grapes', 'other vegetables'],
 ['rolls/buns', 'shopping bags', 'cat food'],
 ['tropical fruit', 'candy'],
 ['citrus fruit', 'dessert'],
 ['root vegetables', 'frozen vegetables', 'bottled water', 'cat food'],
 ['spread cheese', 'pork'],
 ['pip fruit', 'brown bread'],
 ['root vegetables', 'instant coffee'],
 ['soda',
  'hygiene articles',
  'grapes',
  'pudding powder',
  'butter milk',
  'butter'],
 ['whole milk', 'yogurt'],
 ['hamburger meat', 'pasta'],
 ['whole milk', 'processed cheese'],
 ['brown bread', 'sparkling wine'],
 ['rolls/buns', 'other vegetables', 'whipped/sour cream'],
 ['candy', 'white wine'],
 ['root vegetables', 'frozen vegetables'],
 ['other vegetables', 'white bread', 'detergent'],
 ['yogurt', 'beverages', 'brown bread'],
 ['ice cream', 'herbs'],
 ['cream', 'yogurt'],
 ['chicken', 'pastry', 'candles'],
 ['waffles', 'hygiene articles', 'tea'],
 ['yogurt', 'other vegetables', 'rolls/buns', 'herbs'],
 ['yogurt', 'root vegetables'],
 ['domestic eggs', 'yogurt'],
 ['pork', 'whole milk'],
 ['other vegetables', 'white bread'],
 ['bottled water', 'yogurt', 'tropical fruit', 'whole milk'],
 ['citrus fruit', 'misc. beverages'],
 ['liver loaf', 'chicken', 'rolls/buns', 'spread cheese', 'shopping bags'],
 ['citrus fruit', 'misc. beverages'],
 ['whole milk', 'pastry'],
 ['onions', 'newspapers'],
 ['beef', 'specialty fat', 'newspapers'],
 ['rolls/buns', 'semi-finished bread'],
 ['shopping bags', 'rolls/buns'],
 ['pastry', 'canned beer', 'whipped/sour cream', 'grapes'],
 ['salty snack', 'pastry', 'oil'],
 ['frozen potato products', 'specialty cheese'],
 ['brown bread', 'whole milk', 'shopping bags'],
 ['citrus fruit', 'frozen vegetables', 'margarine'],
 ['curd', 'sugar'],
 ['chocolate', 'whole milk'],
 ['pip fruit', 'salty snack', 'pastry'],
 ['pip fruit', 'margarine'],
 ['ham', 'yogurt'],
 ['soda', 'salty snack'],
 ['bottled water', 'chocolate'],
 ['pastry', 'baking powder', 'butter', 'margarine', 'curd', 'dishes'],
 ['whole milk', 'soda'],
 ['pickled vegetables', 'liquor'],
 ['margarine', 'yogurt'],
 ['whole milk', 'frozen vegetables', 'soda', 'UHT-milk'],
 ['other vegetables', 'whipped/sour cream'],
 ['beef', 'semi-finished bread'],
 ['bottled water', 'flour', 'sugar'],
 ['dish cleaner', 'ice cream', 'jam', 'newspapers'],
 ['curd', 'canned beer'],
 ['bottled beer', 'specialty bar', 'baking powder'],
 ['whole milk', 'yogurt', 'newspapers'],
 ['pork', 'pudding powder', 'domestic eggs'],
 ['root vegetables', 'shopping bags'],
 ['misc. beverages', 'UHT-milk', 'white bread'],
 ['dog food', 'sausage', 'dessert', 'shopping bags'],
 ['root vegetables', 'citrus fruit'],
 ['chocolate', 'brown bread', 'salty snack'],
 ['chicken', 'shopping bags'],
 ['other vegetables', 'butter'],
 ['whipped/sour cream', 'yogurt'],
 ['other vegetables', 'yogurt'],
 ['turkey', 'root vegetables'],
 ['other vegetables', 'napkins'],
 ['newspapers', 'white bread', 'rolls/buns', 'beverages'],
 ['other vegetables', 'zwieback'],
 ['brown bread', 'butter milk', 'canned vegetables', 'soda'],
 ['chicken', 'bottled water'],
 ['brown bread', 'soda'],
 ['other vegetables',
  'cream cheese ',
  'liquor',
  'root vegetables',
  'newspapers',
  'hard cheese'],
 ['frankfurter', 'rolls/buns'],
 ['meat', 'whole milk', 'whipped/sour cream'],
 ['bottled beer', 'frozen vegetables', 'sliced cheese'],
 ['pip fruit', 'processed cheese', 'canned beer'],
 ['berries', 'condensed milk'],
 ['house keeping products', 'rolls/buns', 'pickled vegetables', 'curd'],
 ['whole milk', 'hair spray', 'butter', 'pastry'],
 ['ham', 'yogurt'],
 ['grapes', 'whole milk'],
 ['meat', 'other vegetables'],
 ['other vegetables', 'specialty bar'],
 ['soda', 'UHT-milk', 'newspapers', 'white bread'],
 ['citrus fruit', 'brown bread'],
 ['tropical fruit', 'sugar'],
 ['pastry',
  'condensed milk',
  'rice',
  'tropical fruit',
  'chocolate marshmallow'],
 ['coffee', 'shopping bags'],
 ['bottled water', 'citrus fruit'],
 ['root vegetables', 'frozen vegetables'],
 ['chicken', 'dishes'],
 ['rolls/buns', 'oil', 'yogurt'],
 ['pork', 'soda', 'canned vegetables'],
 ['pip fruit', 'whole milk'],
 ['frozen vegetables', 'rolls/buns', 'cling film/bags'],
 ['bottled beer', 'hygiene articles'],
 ['yogurt', 'soda'],
 ['rolls/buns', 'margarine'],
 ['condensed milk', 'shopping bags'],
 ['popcorn', 'citrus fruit'],
 ['sausage', 'pastry'],
 ['root vegetables', 'margarine', 'rolls/buns'],
 ['rolls/buns', 'whipped/sour cream'],
 ['newspapers', 'pork', 'root vegetables', 'napkins'],
 ['misc. beverages', 'whole milk', 'long life bakery product'],
 ['citrus fruit', 'soda'],
 ['soda', 'roll products '],
 ['frankfurter', 'rolls/buns', 'shopping bags', 'margarine'],
 ['other vegetables', 'butter', 'pastry', 'UHT-milk'],
 ['meat', 'coffee'],
 ['frankfurter', 'white bread'],
 ['liquor', 'domestic eggs'],
 ['specialty bar', 'soda', 'frozen vegetables', 'frozen vegetables'],
 ['grapes', 'frozen meals', 'flower (seeds)'],
 ['tea', 'yogurt', 'shopping bags', 'brown bread'],
 ['flower (seeds)', 'white wine'],
 ['cream cheese ', 'specialty chocolate'],
 ['whole milk', 'baking powder'],
 ['margarine', 'soda'],
 ['tropical fruit', 'cream cheese ', 'cream cheese '],
 ['yogurt', 'softener'],
 ['bottled water', 'frankfurter', 'dessert', 'root vegetables'],
 ['other vegetables',
  'semi-finished bread',
  'other vegetables',
  'rolls/buns',
  'shopping bags',
  'salty snack'],
 ['soda', 'whole milk'],

In [46]:
min_n_products = 2
min_support = 0.045
#max_length = max([len(x) for x in transactions])
max_length = 4

In [42]:
data = pd.DataFrame(transactions)
data.head()

,0,1,2,3,4,5,6,7,8,9,10
0,sausage,whole milk,semi-finished bread,yogurt,None,None,None,None,None,None,None
1,whole milk,pastry,salty snack,None,None,None,None,None,None,None,None
2,canned beer,misc. beverages,None,None,None,None,None,None,None,None,None
3,sausage,hygiene articles,None,None,None,None,None,None,None,None,None
4,soda,pickled vegetables,None,None,None,None,None,None,None,None,None

In [47]:
my_eclat = ECLAT(data=data, verbose=True)
rules_indices, rule_supports = my_eclat.fit(min_combination=min_n_products, max_combination=max_length)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 189.23it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 2944.52it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 168/168 [00:00<00:00, 4305.00it/s]

Combination 2 by 2

10it [00:00, 57.00it/s]

Combination 3 by 3

10it [00:00, 54.55it/s]

Combination 4 by 4

5it [00:00, 54.41it/s]

In [49]:
rules_indices,rule_supports

({}, {})